name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Install dependencies
    run: npm install

  - name: Start server
    run: npm start &
    # O "&" coloca o servidor em segundo plano

  - name: Wait for server to be ready
    run: npx wait-on http://127.0.0.1:8080

  - name: Run Cypress tests
    run: npx cypress run